tiles:
- [floor        , floor        , floor             , floor             , floor              , floor         , floor         , floor]
- [floor        , diag_left/W  , linear/W          , 3way_left/W       , linear_stop/W      , linear/W      , diag_left/N   , asphalt]
- [floor        , linear/S     , grass             , linear_stop_both/N, asphalt            , asphalt       , linear/N      , asphalt]
- [floor        , 3way_left/S  , linear_stop_both/W, 3way_left/N       , asphalt            , asphalt       , linear/N      , asphalt]
- [floor        , linear_stop/S, grass             , linear_stop_both/N, asphalt            , diag_right/N  , diag_left/E   , asphalt]
- [floor        , diag_left/S  , linear_stop/E     , 3way_left/E       , linear_stop_left/E , diag_left/E   , asphalt       , asphalt]
- [floor        , floor        , floor             , floor             , floor              , floor         , floor         , floor]


objects:

- kind: duckie
  pos: [2.1, 2.9]
  rotate: 180
  height: 0.08


- kind: sign_blank
  pos: [5.95, 2.2]
  rotate: -60
  height: 0.18

- kind: sign_blank
  pos: [5.95, 3.2]
  rotate: -90
  height: 0.18

- kind: sign_blank
  pos: [5.95, 3.9]
  rotate: -70
  height: 0.18



- kind: truck
  pos: [1.6, 6.3]
  rotate: 0
  height: 0.2
- kind: bus
  pos: [2.0, 0.5]
  rotate: 0
  height: 0.18
- kind: bus
  pos: [4, 0.5]
  rotate: 0
  height: 0.18
- kind: bus
  pos: [6.0, 0.5]
  rotate: 0
  height: 0.18
